### ISSUE TITLE
"no module named utility"

### ISSUE THREAD

**Issue by annaRichImperial** [markoarnauto/biterm#3]
Hi 

I have installed biterm on pycharm, and have the following imports in my code:

import numpy as np
import pyLDAvis
from biterm.cbtm import oBTM
from sklearn.feature_extraction.text import CountVectorizer
from biterm.utility import vec_to_biterms, topic_summuary

however i get the error: 
/homes/ahr18/PycharmProjects/biterm/Source/transformation.py/bin/python /homes/ahr18/PycharmProjects/biterm/Source/biterm.py
Traceback (most recent call last):
  File "/homes/ahr18/PycharmProjects/biterm/Source/biterm.py", line 3, in <module>
    from biterm.cbtm import oBTM
  File "/homes/ahr18/PycharmProjects/biterm/Source/biterm.py", line 3, in <module>
    from biterm.cbtm import oBTM
ImportError: No module named cbtm

Process finished with exit code 1

any idea how i can fix this?

Thanks !

**Comment by XinYue2019** [comment]
annaRichImperial, I've come across the same issue. Have you fixed it yet?

**Comment by markoarnauto** [comment]
Try `from biterm.btm import oBTM` instead of `from biterm.cbtm import oBTM`. If you want to use the cythonic version (cbtm) you have to first compile it yourself.
